# Generated by Django 3.2.4 on 2021-06-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=60)),
                ('quantity_sum', models.IntegerField()),
                ('cost_sum', models.FloatField()),
                ('sell_sum', models.FloatField()),
                ('profit_rupees', models.FloatField()),
                ('profit_percentage', models.FloatField()),
                ('day', models.CharField(max_length=8)),
            ],
        ),
    ]
